# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from DB import infoTable
from views.dialog import CustomDialog

class Ui_EditInfo(object):
    def __init__(self,*args):
        self.idVal = None
        self.locVal = None
        self.startVal = None
        self.endVal = None
        self.residentId = None
        self.isInfoPresent = False
        self.priorityVal = 5
        self.rawMaterialVal = None
        self.machinesVal = None
        self.statisticsVal = None
        if len(args) == 1 and  len(args[0]) == 10:
            args = args[0]
            self.idVal = str(args[0])
            self.locVal = args[1]
            self.startVal = args[2]
            self.endVal = args[3]
            self.residentId = args[4]
            if args[5] is not None:
                self.isInfoPresent = True
            self.priorityVal = args[6] or 5
            self.rawMaterialVal = args[7]
            self.machinesVal = args[8]
            self.statisticsVal = args[9]

    def setupUi(self, EditInfo):
        EditInfo.setObjectName("EditInfo")
        EditInfo.resize(530, 634)
        font = QtGui.QFont()
        font.setPointSize(9)
        EditInfo.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(EditInfo)
        self.buttonBox.setGeometry(QtCore.QRect(270, 580, 231, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(EditInfo)
        self.label.setGeometry(QtCore.QRect(140, 10, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(EditInfo)
        self.line.setGeometry(QtCore.QRect(40, 50, 441, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(EditInfo)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 91, 21))
        self.label_3.setObjectName("label_3")
        self.idInput = QtWidgets.QLineEdit(EditInfo)
        self.idInput.setEnabled(False)
        self.idInput.setGeometry(QtCore.QRect(120, 90, 113, 22))
        self.idInput.setObjectName("idInput")
        self.label_4 = QtWidgets.QLabel(EditInfo)
        self.label_4.setGeometry(QtCore.QRect(260, 90, 71, 21))
        self.label_4.setObjectName("label_4")
        self.roadInput = QtWidgets.QLineEdit(EditInfo)
        self.roadInput.setEnabled(False)
        self.roadInput.setGeometry(QtCore.QRect(342, 90, 151, 22))
        self.roadInput.setObjectName("roadInput")
        self.label_5 = QtWidgets.QLabel(EditInfo)
        self.label_5.setGeometry(QtCore.QRect(30, 140, 91, 21))
        self.label_5.setObjectName("label_5")
        self.startInput = QtWidgets.QLineEdit(EditInfo)
        self.startInput.setEnabled(False)
        self.startInput.setGeometry(QtCore.QRect(102, 140, 141, 22))
        self.startInput.setObjectName("startInput")
        self.label_6 = QtWidgets.QLabel(EditInfo)
        self.label_6.setGeometry(QtCore.QRect(260, 140, 91, 21))
        self.label_6.setObjectName("label_6")
        self.endInput = QtWidgets.QLineEdit(EditInfo)
        self.endInput.setEnabled(False)
        self.endInput.setGeometry(QtCore.QRect(342, 140, 151, 22))
        self.endInput.setObjectName("endInput")
        self.line_2 = QtWidgets.QFrame(EditInfo)
        self.line_2.setGeometry(QtCore.QRect(120, 180, 281, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_7 = QtWidgets.QLabel(EditInfo)
        self.label_7.setGeometry(QtCore.QRect(160, 210, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_2 = QtWidgets.QLabel(EditInfo)
        self.label_2.setGeometry(QtCore.QRect(20, 240, 91, 31))
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(EditInfo)
        self.label_8.setGeometry(QtCore.QRect(20, 350, 91, 31))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(EditInfo)
        self.label_9.setGeometry(QtCore.QRect(20, 450, 91, 31))
        self.label_9.setObjectName("label_9")
        self.rawMaterialInput = QtWidgets.QTextEdit(EditInfo)
        self.rawMaterialInput.setGeometry(QtCore.QRect(120, 250, 371, 91))
        self.rawMaterialInput.setObjectName("rawMaterialInput")
        self.statisticsInput = QtWidgets.QTextEdit(EditInfo)
        self.statisticsInput.setGeometry(QtCore.QRect(120, 460, 371, 91))
        self.statisticsInput.setObjectName("statisticsInput")
        self.machinesInput = QtWidgets.QTextEdit(EditInfo)
        self.machinesInput.setGeometry(QtCore.QRect(120, 360, 371, 91))
        self.machinesInput.setObjectName("machinesInput")
        self.spinBox = QtWidgets.QSpinBox(EditInfo)
        self.spinBox.setGeometry(QtCore.QRect(250, 210, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox.setFont(font)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(5)
        self.spinBox.setObjectName("spinBox")

        self.retranslateUi(EditInfo)
        self.buttonBox.accepted.connect(lambda :self.makeEdits(EditInfo))
        self.buttonBox.rejected.connect(EditInfo.reject)
        QtCore.QMetaObject.connectSlotsByName(EditInfo)

    def retranslateUi(self, EditInfo):
        _translate = QtCore.QCoreApplication.translate
        EditInfo.setWindowTitle(_translate("EditInfo", "edit repair info"))
        self.label.setText(_translate("EditInfo", "Edit Road Repair Info"))
        self.label_3.setText(_translate("EditInfo", "Complaint Id:"))
        self.idInput.setText(_translate("EditInfo", self.idVal))
        self.label_4.setText(_translate("EditInfo", "Road Loc:"))
        self.roadInput.setText(_translate("EditInfo", self.locVal))
        self.label_5.setText(_translate("EditInfo", "StartLoc:"))
        self.startInput.setText(_translate("EditInfo", self.startVal))
        self.label_6.setText(_translate("EditInfo", "EndLoc:"))
        self.endInput.setText(_translate("EditInfo", self.endVal))
        self.label_7.setText(_translate("EditInfo", "Priority:"))
        self.spinBox.setValue(self.priorityVal)
        self.label_2.setText(_translate("EditInfo", "Raw Material:"))
        self.rawMaterialInput.setText(_translate("ShowInfo",self.rawMaterialVal))
        self.label_8.setText(_translate("EditInfo", "Machines:"))
        self.machinesInput.setText(_translate("ShowInfo",self.machinesVal))
        self.label_9.setText(_translate("EditInfo", "Statistics:"))
        self.statisticsInput.setText(_translate("ShowInfo",self.statisticsVal))

    def makeEdits(self,win):
        mapping = {
            'complainId' : self.idVal,
            'priority' : self.spinBox.value(),
            "rawMaterial" : self.rawMaterialInput.toPlainText(),
            "machines" : self.machinesInput.toPlainText(),
            "statistics" : self.statisticsInput.toPlainText()
        }

        try:
            if self.isInfoPresent:
                infoTable.updateComplaintInfo(mapping)
            else:
                infoTable.makeComplaintInfo(mapping)
            win.accept()
        except Exception as e:
            print(e)
            dialog = CustomDialog("Error",str(e),'critical')
            dialog.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditInfo = QtWidgets.QDialog()
    ui = Ui_EditInfo()
    ui.setupUi(EditInfo)
    EditInfo.show()
    sys.exit(app.exec_())
