# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mayor.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from views.mayor.showStats import Ui_showStatus
from DB import scheduleTable


class Ui_MainMayor(object):
    def setupUi(self, MainMayor):
        MainMayor.setObjectName("MainMayor")
        MainMayor.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainMayor.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainMayor)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 10, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 90, 731, 451))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(194, 194, 194))
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(194, 194, 194))
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(194, 194, 194))
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(194, 194, 194))
        self.tableWidget.setHorizontalHeaderItem(4, item)

        header = self.tableWidget.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(4,QtWidgets.QHeaderView.ResizeToContents)

        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainMayor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainMayor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainMayor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainMayor)
        self.statusbar.setObjectName("statusbar")
        MainMayor.setStatusBar(self.statusbar)
        self.actionDevelopers = QtWidgets.QAction(MainMayor)
        self.actionDevelopers.setObjectName("actionDevelopers")
        self.menuAbout.addAction(self.actionDevelopers)
        self.menubar.addAction(self.menuMain.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainMayor)
        QtCore.QMetaObject.connectSlotsByName(MainMayor)

    def retranslateUi(self, MainMayor):
        _translate = QtCore.QCoreApplication.translate
        MainMayor.setWindowTitle(_translate("MainMayor", "mayor main"))
        self.label.setText(_translate("MainMayor", "Mayor"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainMayor", "ComplaintId"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainMayor", "RoadLoc"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainMayor", "Start Loc"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainMayor", "End Loc"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainMayor", "statistics"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.updateTable(MainMayor)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainMayor", "Road Repair Schedule:"))
        self.menuMain.setTitle(_translate("MainMayor", "Main"))
        self.menuAbout.setTitle(_translate("MainMayor", "About"))
        self.actionDevelopers.setText(_translate("MainMayor", "Developers"))

    def updateTable(self,win):
        _translate = QtCore.QCoreApplication.translate
        self.schedule = scheduleTable.getSchedule()

        self.tableWidget.setRowCount(len(self.schedule))
        getitems = (0,1,2,3)
        for i,t in enumerate(self.schedule):
            item = QtWidgets.QTableWidgetItem()
            item.setText(str(i+1))
            self.tableWidget.setVerticalHeaderItem(i, item)
            for j,idx in enumerate(getitems):
                item = QtWidgets.QTableWidgetItem()
                item.setText(_translate("MainSupervisor", str(t[idx])))
                self.tableWidget.setItem(i, j, item)

            item = QtWidgets.QPushButton()
            item.setText('show stats of id: ' + str(t[0]))
            item.clicked.connect(lambda : self.showStats(win,t[0],t[9]))
            self.tableWidget.setCellWidget(i, 4, item)

    def showStats(self,win,id,stats):
        showStatus = QtWidgets.QDialog(win)
        ui = Ui_showStatus(id,stats)
        ui.setupUi(showStatus)
        showStatus.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainMayor = QtWidgets.QMainWindow()
    ui = Ui_MainMayor()
    ui.setupUi(MainMayor)
    MainMayor.show()
    sys.exit(app.exec_())
