# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'showStats.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_showStatus(object):
    def __init__(self,id,stats):
        self.id = id
        self.stats = stats

    def setupUi(self, showStatus):
        showStatus.setObjectName("showStatus")
        showStatus.resize(400, 300)
        font = QtGui.QFont()
        font.setPointSize(9)
        showStatus.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(showStatus)
        self.buttonBox.setGeometry(QtCore.QRect(30, 260, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(showStatus)
        self.label.setGeometry(QtCore.QRect(110, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(showStatus)
        self.textBrowser.setGeometry(QtCore.QRect(10, 50, 371, 191))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(showStatus)
        self.buttonBox.accepted.connect(showStatus.accept)
        self.buttonBox.rejected.connect(showStatus.reject)
        QtCore.QMetaObject.connectSlotsByName(showStatus)

    def retranslateUi(self, showStatus):
        _translate = QtCore.QCoreApplication.translate
        showStatus.setWindowTitle(_translate("showStatus", "view stats"))
        self.label.setText(_translate("showStatus", "ComplaintId : " + str(self.id)))
        self.textBrowser.setText(_translate("showStatus",self.stats))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    showStatus = QtWidgets.QDialog()
    ui = Ui_showStatus()
    ui.setupUi(showStatus)
    showStatus.show()
    sys.exit(app.exec_())
