# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'roadInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def __init__(self):
        super().__init__()
        self.roadLoc = None
        self.roadStart = None
        self.roadEnd = None

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(388, 322)
        font = QtGui.QFont()
        font.setPointSize(9)
        Dialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 270, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(70, 60, 231, 211))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.locRoadInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.locRoadInput.setObjectName("locRoadInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.locRoadInput)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.startingPointInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.startingPointInput.setObjectName("startingPointInput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.startingPointInput)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.endingPointInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.endingPointInput.setObjectName("endingPointInput")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.endingPointInput)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.SpanningRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.SpanningRole, spacerItem2)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(70, 0, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.residentName = QtWidgets.QLabel(Dialog)
        self.residentName.setGeometry(QtCore.QRect(70, 30, 221, 16))
        self.residentName.setObjectName("residentName")

        self.retranslateUi(Dialog)
        # self.accepted.connect(self.updateValues)

        self.buttonBox.accepted.connect(lambda : self.updateValues(Dialog))
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Loc of Road"))
        self.label_2.setText(_translate("Dialog", "Starting point"))
        self.label_3.setText(_translate("Dialog", "Ending Point"))
        self.label_4.setText(_translate("Dialog", "Enter Info about the road"))
        if self.residentStr:
            self.residentName.setText(_translate("Dialog", "By: " + self.residentStr))

    def updateValues(self,Device):
        print('update')
        Device.roadLoc = self.locRoadInput.text()
        Device.roadStart = self.startingPointInput.text()
        Device.roadEnd = self.endingPointInput.text()
        Device.accept()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
