# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectResidents.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator
from views.dialog import CustomDialog
from views.residents.roadInfo import Ui_Dialog
import DB

class Ui_ResidentsWindow(QtWidgets.QMainWindow):
    # def __init__(self,par):
    #     super().__init__(par)
    #     self.setupUi(par)


    def setupUi(self, ResidentsWindow):
        ResidentsWindow.setObjectName("ResidentsWindow")
        ResidentsWindow.resize(800, 600)
        ResidentsWindow.setFixedSize(800,600)
        self.centralwidget = QtWidgets.QWidget(ResidentsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.residentLabel = QtWidgets.QLabel(self.centralwidget)
        self.residentLabel.setGeometry(QtCore.QRect(330, 0, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setUnderline(True)
        self.residentLabel.setFont(font)
        self.residentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.residentLabel.setObjectName("residentLabel")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 781, 501))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")

        self.residentsList = QtWidgets.QListWidget(self.groupBox)
        self.residentsList.setGeometry(QtCore.QRect(400, 0, 381, 461))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.residentsList.setFont(font)
        self.residentsList.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.residentsList.setObjectName("residentsList")

        self.newResidentsLabel = QtWidgets.QLabel(self.groupBox)
        self.newResidentsLabel.setGeometry(QtCore.QRect(120, 10, 151, 21))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setItalic(False)
        self.newResidentsLabel.setFont(font)
        self.newResidentsLabel.setObjectName("newResidentsLabel")
        self.nameLabel = QtWidgets.QLabel(self.groupBox)
        self.nameLabel.setGeometry(QtCore.QRect(50, 60, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.nameInput = QtWidgets.QLineEdit(self.groupBox)
        self.nameInput.setGeometry(QtCore.QRect(110, 60, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nameInput.setFont(font)
        self.nameInput.setObjectName("nameInput")
        self.idInput = QtWidgets.QLineEdit(self.groupBox)
        self.idInput.setGeometry(QtCore.QRect(110, 110, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.idInput.setFont(font)
        self.idInput.setAutoFillBackground(False)
        self.idInput.setInputMask("")
        self.idInput.setText("")
        self.idInput.setCursorPosition(0)
        self.idInput.setPlaceholderText("")
        self.idInput.setObjectName("idInput")
        self.idLabel = QtWidgets.QLabel(self.groupBox)
        self.idLabel.setGeometry(QtCore.QRect(40, 110, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.idLabel.setFont(font)
        self.idLabel.setObjectName("idLabel")
        self.addressLabel = QtWidgets.QLabel(self.groupBox)
        self.addressLabel.setGeometry(QtCore.QRect(30, 160, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addressLabel.setFont(font)
        self.addressLabel.setObjectName("addressLabel")
        self.addressInput = QtWidgets.QTextEdit(self.groupBox)
        self.addressInput.setGeometry(QtCore.QRect(110, 160, 241, 91))
        self.addressInput.setObjectName("addressInput")
        self.phoneLabel = QtWidgets.QLabel(self.groupBox)
        self.phoneLabel.setGeometry(QtCore.QRect(20, 280, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.phoneLabel.setFont(font)
        self.phoneLabel.setObjectName("phoneLabel")
        self.phoneInput = QtWidgets.QLineEdit(self.groupBox)
        self.phoneInput.setGeometry(QtCore.QRect(110, 280, 241, 31))
        self.phoneInput.setValidator(QIntValidator())
        font = QtGui.QFont()
        font.setPointSize(10)
        self.phoneInput.setFont(font)
        self.phoneInput.setObjectName("phoneInput")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(250, 360, 101, 41))
        self.pushButton.clicked.connect(self.addResident)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.ResetButton = QtWidgets.QPushButton(self.groupBox)
        self.ResetButton.setGeometry(QtCore.QRect(30, 367, 93, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.ResetButton.setFont(font)
        self.ResetButton.setObjectName("ResetButton")
        self.ResetButton.clicked.connect(self.resetInputs)

        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(380, 0, 20, 501))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setGeometry(QtCore.QRect(0, 40, 391, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.selectButton = QtWidgets.QPushButton(self.groupBox)
        self.selectButton.setGeometry(QtCore.QRect(660, 470, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(10)
        self.selectButton.setFont(font)
        self.selectButton.setObjectName("selectButton")
        self.selectButton.clicked.connect(lambda : self.openRoadInfoDialog(ResidentsWindow))

        ResidentsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ResidentsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        ResidentsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ResidentsWindow)
        self.statusbar.setObjectName("statusbar")
        ResidentsWindow.setStatusBar(self.statusbar)
        self.actionDevelopers = QtWidgets.QAction(ResidentsWindow)
        self.actionDevelopers.setObjectName("actionDevelopers")
        self.menuAbout.addAction(self.actionDevelopers)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(ResidentsWindow)
        QtCore.QMetaObject.connectSlotsByName(ResidentsWindow)

    def retranslateUi(self, ResidentsWindow):
        _translate = QtCore.QCoreApplication.translate
        ResidentsWindow.setWindowTitle(_translate("ResidentsWindow", "MainWindow"))
        self.residentLabel.setText(_translate("ResidentsWindow", "Residents"))
        __sortingEnabled = self.residentsList.isSortingEnabled()
        self.residentsList.setSortingEnabled(False)

        self.updateResidentsList()

        self.residentsList.setSortingEnabled(__sortingEnabled)
        self.newResidentsLabel.setText(_translate("ResidentsWindow", "New Registation "))
        self.nameLabel.setText(_translate("ResidentsWindow", "Name : "))
        self.idLabel.setText(_translate("ResidentsWindow", "Govt Id :"))
        self.addressLabel.setText(_translate("ResidentsWindow", "Address :"))
        self.phoneLabel.setText(_translate("ResidentsWindow", "Phone No :"))
        self.pushButton.setText(_translate("ResidentsWindow", "Create"))
        self.ResetButton.setText(_translate("ResidentsWindow", "Reset"))
        self.selectButton.setText(_translate("ResidentsWindow", "Select"))
        self.menuMenu.setTitle(_translate("ResidentsWindow", "Menu"))
        self.menuAbout.setTitle(_translate("ResidentsWindow", "About"))
        self.actionDevelopers.setText(_translate("ResidentsWindow", "Developers"))

    def makeComplaint(self,resId,roadLoc,startingPoint,endingPoint):
        if not resId: raise ValueError('res Id not found in makeComplaint')
        missing = []
        if not roadLoc: missing.append('roadLoc')
        if not startingPoint or not endingPoint: missing.append('start/end point')
        if len(missing) > 0:
            msg = CustomDialog.init_message('Values Missing', '{0} is/are Missing'.format(' ,'.join(missing)), 'critical')
            msg.exec_()
        else:
            try:
                val = DB.complainTable.makeComplaint(resId,roadLoc,startingPoint,endingPoint)
                msg = CustomDialog.init_message('Success', 'New Complaint registed successfully, with Complaint ID : {}'.format(val))
                msg.exec_()
            except Exception as e:
                msg = CustomDialog.init_message('DB Error', str(e),'critical')
                msg.exec_()

    def openRoadInfoDialog(self,win):
        Dialog = QtWidgets.QDialog(win)
        ui = Ui_Dialog()
        ui.residentStr = self.residentsList.currentItem().text()
        ui.setupUi(Dialog)
        Dialog.show()
        resident = self.residentsList.currentItem().resident

        if Dialog.exec() == QtWidgets.QDialog.Accepted:
            resId , name, idCardNo, address, phoneNo = resident
            roadLoc = Dialog.roadLoc
            roadStart = Dialog.roadStart
            roadEnd = Dialog.roadEnd
            val = self.makeComplaint(resId, roadLoc, roadStart, roadEnd)



    def updateResidentsList(self):
        _translate = QtCore.QCoreApplication.translate
        self.residentsList.clear()
        self.residentsRows = DB.residentTable.getAllResident()
        for resident in self.residentsRows:
            item = QtWidgets.QListWidgetItem()
            item.resident = resident
            item.setText(_translate("ResidentsWindow", resident[1] + ' - ' + str(resident[4]) ))
            self.residentsList.addItem(item)

    def addResident(self):
        missing = []
        name = self.nameInput.text()
        if not name: missing.append('name')
        id = self.idInput.text()
        if not id: missing.append('GovtId')
        address = self.addressInput.toPlainText()
        if not address: missing.append('Address')
        phoneNo = self.phoneInput.text()
        if not phoneNo: missing.append('phoneNo')
        phoneNo = int(phoneNo)
        if len(missing) > 0:
            msg = CustomDialog.init_message('Values Missing','{0} is/are Missing'.format(' ,'.join(missing)),'warning')
            msg.exec_()
        else:
            DB.residentTable.insertNewResident(name,id,address,phoneNo)
            self.updateResidentsList()

    def resetInputs(self):
        self.nameInput.clear()
        self.idInput.clear()
        self.addressInput.clear()
        self.phoneInput.clear()


def launchResidents():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ResidentsWindow = QtWidgets.QMainWindow()
    try:
        ui = Ui_ResidentsWindow()
        ui.setupUi(ResidentsWindow)
        ResidentsWindow.show()
    except Exception as e:
        dialog = CustomDialog.init(ResidentsWindow, 'Error', str(e))
        if dialog.show():
            dialog.close()
        else:
            ResidentsWindow.show()
    finally:
        sys.exit(app.exec_())


if __name__ == "__main__":
    launchResidents()