# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminstration.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from views.dialog import CustomDialog
from DB import infoTable

class Ui_AdminstrationWindow(object):
    def __init__(self,*args):
        print(args)
        self.idVal = None
        self.locVal = None
        self.startVal = None
        self.endVal = None
        self.residentId = None
        self.priorityVal = None
        self.isInfoPresent = False
        self.rawMaterialVal = None
        self.machinesVal = None
        self.statisticsVal = None
        if len(args) == 1 and  len(args[0]) == 10:
            args = args[0]
            self.idVal = args[0]
            self.locVal = args[1]
            self.startVal = args[2]
            self.endVal = args[3]
            self.residentId = args[4]
            if args[5] is not None:
                self.isInfoPresent = True
            self.priorityVal = str(args[6])
            self.rawMaterialVal = args[7]
            self.machinesVal = args[8]
            self.statisticsVal = args[9]

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        MainWindow.setFixedSize(600,600)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 0, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 290, 581, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.rawMaterialInput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.rawMaterialInput.setGeometry(QtCore.QRect(200, 120, 341, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rawMaterialInput.setFont(font)
        self.rawMaterialInput.setObjectName("rawMaterialInput")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 90, 221, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 330, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.machineInput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.machineInput.setGeometry(QtCore.QRect(200, 320, 341, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.machineInput.setFont(font)
        self.machineInput.setObjectName("machineInput")
        self.updateBtn = QtWidgets.QPushButton(self.centralwidget)
        self.updateBtn.setGeometry(QtCore.QRect(410, 490, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.updateBtn.setFont(font)
        self.updateBtn.setMouseTracking(True)
        self.updateBtn.setObjectName("updateBtn")
        self.updateBtn.clicked.connect(lambda :self.addResources(MainWindow))


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 599, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actiondevelopers = QtWidgets.QAction(MainWindow)
        self.actiondevelopers.setObjectName("actiondevelopers")
        self.menuAbout.addAction(self.actiondevelopers)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Adminstration"))
        self.label_2.setText(_translate("MainWindow", "Update Resources :"))
        self.label_3.setText(_translate("MainWindow", " Available rawMaterial:"))

        self.label_4.setText(_translate("MainWindow", "Available Machines:"))
        self.updateBtn.setText(_translate("MainWindow", "Update"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actiondevelopers.setText(_translate("MainWindow", "developers"))
        
        # SET VALUES FROM DB

        self.rawMaterialInput.setPlainText(_translate("MainWindow", self.rawMaterialVal))
        self.machineInput.setPlainText(_translate("MainWindow", self.machinesVal))

        if self.isInfoPresent:
            val = infoTable.getComplaintInfo(str(self.idVal))
            print(val)

    def addResources(self,win):
        rawMaterial = self.rawMaterialInput.toPlainText()
        machine = self.machineInput.toPlainText()
        mapping = {
            'complainId' : self.idVal,
            'rawMaterial' : rawMaterial,
            'machines' : machine
        }
        print(mapping)
        try:
            if self.isInfoPresent:
                infoTable.updateMaterialInfo(mapping)
            else:
                infoTable.makeMaterialInfo(mapping)
            msg = CustomDialog.init_message('Success', 'Database Updated')
            if msg.exec_():
                win.close()

        except Exception as e:
            print(e)
            msg = CustomDialog.init_message('Warning', str(e), 'warning')
            msg.exec_()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_AdminstrationWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
